report failure if we fail to launch the new container instance

diff --git a/ecs-deploy b/ecs-deploy
--- a/ecs-deploy
+++ b/ecs-deploy
@@ -181,3 +181,7 @@ do
   sleep $every
   i=$(( $i + $every ))
 done
+
+SERVICE=${SERVICE} CLUSTER=${CLUSTER} IMAGE=${IMAGE} ./slack_notification.sh
+echo "Service failed to deploy successfully";
+exit 1
